version: "3.9"

services:
  mongo:
    image: mongo:7
    container_name: mongo-medical
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
      MONGO_INITDB_DATABASE: medicaldb
    volumes:
      - mongo_data:/data/db
      - ./mongo/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    ports:
      - "27017:27017"

  migrator:
    build: ./migration
    container_name: migrator-medical
    depends_on:
      - mongo
    environment:
      MONGO_URI: mongodb://app_user:app_password@mongo:27017/medicaldb?authSource=medicaldb
      DATASET_PATH: /csv/healthcare_dataset.csv
    volumes:
      - ./data:/csv
    command: ["python", "migrate.py"]

volumes:
  mongo_data:
